### ISSUE TITLE
age.bed in source dir is not correct for hg38

### ISSUE THREAD

**Issue by jeftreece** [jazdrv/dnaTools#5]
age.bed needs to be reviewed and corrected

**Comment by moregubbins** [comment]
The new plan is ultimately to do away with age.bed (leaving it as an optional restriction). For now, we can liftOver the current Build 37 co-ordinates to Build 38 (still to do).

**Comment by jeftreece** [comment]
I have converted age.bed to hg38, whether it's needed or not, so I'll close this issue. It may resurface again if it's needed for anything. [sqldev 44dfea6]
